#!/bin/bash
#
# This is so simple that we use bash
#
# Copyright - Ruben Olsen Lærk - RubenOlsen@github
#


for a in  core plugins
do 
  echo Processing: $a 
  file=../_data/demo$a.csv
  rm $file
  echo "filename" >> $file
  find ../demo/$a | grep ".html" | cut -d "/" -f 4 | cut -d "." -f 1  >> $file
done

